import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import ContextProvider from "./ContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <main className="bg-[#fcfcfc]">{children}</main>
        </ContextProvider>

        <Script src="/scripts/dialog.js" strategy="beforeInteractive"></Script>
        {/* <Script src="https://unpkg.com/@material-tailwind/html@latest/scripts/dialog.js"></Script> */}
      </body>
    </html>
  );
}
