import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="bg-[#fcfcfc]">{children}</main>

        <Script src="node_modules/@material-tailwind/html@latest/scripts/dialog.js"></Script>
        <Script src="https://unpkg.com/@material-tailwind/html@latest/scripts/dialog.js"></Script>
      </body>
    </html>
  );
}
